### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by cloudguyxyz** [sgt7io/github-crash-course#1]
I think ti looks better if the main title is a bit more orange.

```css
h1 {
  color: #efa82e;
}
```
